# -*- mode: yaml -*-
# vi: set ft=yaml :

---
- hosts: all
  gather_facts: false
  become: true
  tasks:
    - include: docker.yml

    - name: check swarm is active
      shell: 'docker info | grep "Swarm: active"'
      register: swarm_active
      ignore_errors: true

    - name: swarm init
      when: swarm_active.rc == 1
      shell: docker swarm init --listen-addr {{ manager_ip }}:2377 --advertise-addr {{ manager_ip }}

    - name: get swarm token
      shell: docker swarm join-token -q worker > /vagrant/worker_token
